server:
  port: "8080"
  mode: "debug"  # debug, release, test
  read_timeout: 30
  write_timeout: 30

database:
  driver: "mysql"
  host: "localhost"
  port: "13306"
  username: "root"
  password: "root"
  database: "my_demo"
  charset: "utf8mb4"

jwt:
  secret: "your-jwt-secret-key"
  expire_time: 24  # hours

log:
  level: "info"  # debug, info, warn, error
  path: "./logs"

redis:
  host: "localhost"
  port: "6379"
  password: ""
  db: 0